### PR TITLE
Fixing new class path in pom generating the Java files from xsd

### PR DESCRIPTION
**Pull request by ibaldin**
Missed orca/nodeagent vs org.renci.nodeagent path in pom file and corresponding Java files from xsd

### CODE REVIEW

**Comment by ibaldin** [comment]
Also I wonder if we should remove some of those directories from git since the Java code is Auto generated from xsd

**Comment by hinchliff** [comment]
Yes, in general the best practice is to not check in generated files (like from JAXB).  I deleted those files from git, updated the `.gitignore`, and confirmed that the project still builds (generating files as necessary).

**Comment by hinchliff** [comment]
Should we change this `log4j-default.properties` path in [ServerMain](https://github.com/RENCI-NRIG/nodeagent2/blob/master/agent/server/src/main/java/org/renci/nodeagent2/agent/server/ServerMain.java#L22)?

**Comment by ibaldin** [comment]
This line is going away in the new code with the switch to the log4j2. I'm going to merge this branch and delete it - the new branch for new Spring version will take care of the rest.

**Pull request merged**
